---
title: "Lesson 2: Geospatial Data Science and Visualisation"
date: "February 21, 2023"
date-modified: "last-modified"
format: html
toc: true
---

## Overview

In this lesson, R objects used to import, integrate, wrangle, process and visualise geospatial data will be discussed. The discussion will focus on `sf` and `tmap` packages. Other R packages for storing (i.e. sp), transforming (i.e. rgdal) and processing (i.e. rgeos) geospatial data will be discussed briefly too.

## Content

-   Geospatial Visualisation
    -   Classification of maps
    -   Principles of map design
    -   Thematic mapping techniques
    -   Analytical mapping techniques

## Lesson Slides

-   [Lesson 2: GeoVisualisation and Analytical Mapping](..\lesson\Lesson02\Lesson02-GeoVis.html) slides.

## Hands-on Exercise

-   [Geospatial Data Wrangling with R](https://r4gdsa.netlify.app/chap01.html)
-   [Choropleth Mapping with R](https://r4gdsa.netlify.app/chap02.html)

### Self-reading Before Meet-up

To read before class:

-   [Proportional Symbols](https://www.axismaps.com/guide/univariate/proportional-symbols/)
-   [Choropleth Maps](https://en.wikipedia.org/wiki/Choropleth_map%20Choropleth%20map)
-   [The Basics of Data Classification](https://www.axismaps.com/guide/data/data-classification/)
-   [Choropleth Mapping with Exploratory Data Analysis](https://www.directionsmag.com/article/3363)
-   Tennekes, M. (2018) "[tmap: Thematic Maps in R](https://www.jstatsoft.org/article/view/v084i06)", *Journal of Statistical Software*, Vol 84:6, 1-39.

## All About R

-   [sf](https://r-spatial.github.io/sf/) package.

    -   [Simple Features for R](https://r-spatial.github.io/sf/articles/sf1.html)
    -   [Reading, Writing and Converting Simple Features](https://r-spatial.github.io/sf/articles/sf2.html)
    -   [Manipulating Simple Feature Geometries](https://r-spatial.github.io/sf/articles/sf3.html)
    -   [Manipulating Simple Features](https://r-spatial.github.io/sf/articles/sf4.html)

-   [tmap: thematic maps in R](https://r-tmap.github.io/tmap/) package especially:

    -   [tmap: get started!](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html),
    -   [tmap: version changes](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-changes.html), and
    -   [Chapter 8 Making maps with R](https://geocompr.robinlovelace.net/adv-map.html) of Geocomputation with R.

## Reference

-   [The Concept of Map Symbols](https://www.yaaka.cc/unit/the-concept-of-map-symbols/)
-   [Choropleth map](https://en.wikipedia.org/wiki/Choropleth_map)
-   [Choropleth Maps -- A Guide to Data Classification](https://gisgeography.com/choropleth-maps-data-classification/)
-   [Bivariate Choropleth](https://www.axismaps.com/guide/multivariate/bivariate-choropleth/)
-   [Value-by-alpha maps](http://andywoodruff.com/blog/value-by-alpha-maps/)
-   [What to consider when creating choropleth maps](https://blog.datawrapper.de/choroplethmaps/)
